export const createAction = type => payload =>  {
    return {
        type: type,
        $payload: payload || {},
    };
};

export const types = {
    GET_MESSAGES: 'GET_MESSAGES',
    SET_MESSAGES: 'SET_MESSAGES',
    CLEAR_MESSAGES: 'CLEAR_MESSAGES',
    ADD_MESSAGE: 'ADD_MESSAGE',
    SET_SENDED_MESSAGE: 'SET_SENDED_MESSAGE',

    GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
    SET_NOTIFICATIONS: 'SET_NOTIFICATIONS',
    CLEAR_NOTIFICATIONS: 'CLEAR_NOTIFICATIONS',

    GET_CONTACTS: 'GET_CONTACTS',
    SET_CONTACTS: 'SET_CONTACTS',
    CLEAR_LOADING: 'CLEAR_LOADING',
    SET_LOADING: 'SET_LOADING',
    CLEAR_CONTACTS: 'CLEAR_CONTACTS',
    SET_ACTIVE_CONTACT: 'SET_ACTIVE_CONTACT',
    CLEAR_ACTIVE_CONTACT: 'CLEAR_ACTIVE_CONTACT',
}
